language: d

os:
    - linux
    - osx

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.088.0
  - dmd-2.078.3
  - ldc-1.17.0
  - ldc-1.16.0
  - ldc-1.15.0
  - ldc-1.14.0
  - ldc-1.9.0
  - dmd-2.087.1
  - dmd-2.086.1
  - dmd-2.085.1
  - dmd-2.079.0
  - dmd-beta

env:
    - CONFIG=select
    - CONFIG=epoll
    - CONFIG=kqueue
    # disabled until the libasync driver of eventcore is more than a stub
    #- CONFIG=libasync

matrix:
  allow_failures:
    - env: CONFIG=libasync
    - d: dmd-beta
  exclude:
      - os: linux
        env: CONFIG=kqueue
      - os: osx
        env: CONFIG=epoll
  include:
    - d: dmd
      env: CONFIG='select' DUB_FLAGS='--build unittest-cov --build-mode=singleFile'
    - d: dmd
      env: CONFIG='select' DUB_FLAGS='--build unittest-cov --build-mode=singleFile'
    - d: dmd
      env: CONFIG='select' DUB_FLAGS='--build unittest-cov --build-mode=singleFile'

branches:
  only:
    - master

before_install:
  - wget https://dlang.org/install.sh -O ~/dlang/install.dub.sh
  - . $(bash ~/dlang/install.dub.sh -a dub)
  - dub --version

script: ./travis-ci.sh

sudo: false

after_success:
 - bash <(curl -s https://codecov.io/bash)
